name: CD

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0 
        with:
          host: ${{ vars.SERVER_IP }} 
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/cesusc-devops
            docker compose down
            docker rmi ffeller/cesusc-devops:latest
            docker compose up -d
            docker system prune -a
