name: CD

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install # necessário caso haja alteração nas dependências do projeto

      - name: Deploy the application
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /opt/cesusc-devops/ # Pasta onde está o nosso projeto
          remote_host: ${{ vars.SERVER_IP }} # Aqui vai o IP da instância EC2 guardado na variavel do repositorio
          remote_user: ${{ secrets.USER_NAME }} 
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

  zap_scan:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://${{ vars.SERVER_IP }}'

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html          
